# Generated by Django 5.0.4 on 2024-04-10 13:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('timetotal', models.IntegerField()),
                ('path', models.CharField()),
                ('comments', models.ManyToManyField(related_name='comment_runs', through='main_app.Comment', to='main_app.profile')),
                ('likes', models.ManyToManyField(related_name='liked_runs', through='main_app.Like', to='main_app.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.run'),
        ),
        migrations.AddField(
            model_name='comment',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.run'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='main_app.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='main_app.profile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
