# Generated by Django 5.0.4 on 2024-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='run',
            name='starttime',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='run',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment_runs', through='main_app.Comment', to='main_app.profile'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_runs', through='main_app.Like', to='main_app.profile'),
        ),
    ]
